# Generated by Django 3.2 on 2021-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ActivityID')),
                ('act_name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('PROJ', 'Project'), ('INIT', 'Initiative')], max_length=4)),
                ('start', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Halted', 'Halted'), ('Abandoned', 'Abandoned')], max_length=9)),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('region', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('constituency', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('mid', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='MinID')),
                ('name', models.CharField(max_length=30)),
                ('est', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('abname', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('est', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParlMember',
            fields=[
                ('persnr', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='PersNr')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('year_elect', models.DateField()),
                ('no_terms', models.IntegerField()),
                ('elected_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='records.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('persnr', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='PersNr')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('rank', models.CharField(choices=[('MIN', 'Minister'), ('DEP', 'Deputy Minister')], max_length=3)),
                ('appointed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.ministry')),
            ],
        ),
    ]
