# Generated by Django 3.2 on 2021-08-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210823_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minister',
            options={'ordering': ('rank', 'surname', 'first_name'), 'verbose_name': 'Minister', 'verbose_name_plural': 'Ministers'},
        ),
        migrations.AlterModelOptions(
            name='parlmember',
            options={'ordering': ('surname', 'first_name', 'elected_to'), 'verbose_name': 'MP', 'verbose_name_plural': 'MPs'},
        ),
        migrations.RenameField(
            model_name='minister',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='parlmember',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='parlmember',
            name='no_terms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
